name: NPM Publish
'on':
  push:
    tags:
      - 'v*.*.*'

jobs:
  build_lib:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Install
        run: npm ci --legacy-peer-deps --ignore-scripts
      - name: Test
        run: npm run test:ci
      - name: Build
        run: npm run build && npm run build:lib
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: ng-qrcode-svg
          path: dist/ng-qrcode-svg

  publish_npm:
    needs:
      - build_lib
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Download
        uses: actions/download-artifact@v2
        with:
          name: ng-qrcode-svg
          path: /tmp/ng-qrcode-svg
      - name: Publish
        run: |
          cd /tmp/ng-qrcode-svg
          ls -ltra .
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
